### ISSUE TITLE
设置了白名单依然无法阻止ApiGroupAuth拦截

### ISSUE THREAD

**Issue by waterhark** [easy-swoole/http-annotation#3]
![image](https://user-images.githubusercontent.com/8331582/90871919-6970f500-e3ce-11ea-9c48-0706635531ca.png)
![image](https://user-images.githubusercontent.com/8331582/90872009-8b6a7780-e3ce-11ea-934e-53d64b8f159f.png)

**Comment by kiss291323003** [comment]
注解参数已经支持了ignoreAction属性
